### ISSUE TITLE
no ouput found after executing tiles.py. Getting local.Error: unsupported local setting

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [foozmeat/tiles#1]
I have follow these steps

[pip install -r requirements.txt
copy config.yaml.sample config.yaml
tiles.py](url)

Actually, there is no output.html accept output.html.j2

**Comment by foozmeat** [comment]
Hi @MuhammadFaizanKhan the directions work OK for me. Are you using python 2 or 3?

**Comment by MuhammadFaizanKhan** [comment]
python 2

**Comment by MuhammadFaizanKhan** [comment]
Oh sorry. . Yesterday the command python `tiles.py` was running without any output or error but today I am getting this command as i executed the script (python tiles.py) again. 

> python tiles.py
> Traceback (most recent call last):
>   File "tiles.py", line 17, in <module>
>     locale.setlocale(locale.LC_ALL, config['locale'])
>   File "C:\Python27\lib\locale.py", line 581, in setlocale
>     return _setlocale(category, locale)
> locale.Error: unsupported locale setting

I am using python.2.7

**Comment by foozmeat** [comment]
Since you're on Windows try changing the locale settings in `config.py` to `English_United States.1252` or whatever locale is appropriate for where you are.

**Comment by MuhammadFaizanKhan** [comment]
Thanks, i tried your solution but the problem still persist. First i got locale settings through this code snippet
```
import ctypes
import locale
windll = ctypes.windll.kernel32

print windll.GetUserDefaultUILanguage()

print locale.windows_locale[ windll.GetUserDefaultUILanguage() ]
```
Then i set this in second line of config.yaml
`locale: 'en_US.1033'`

While my current system locale is selected  to **English (United States)**. I don't know what i am doing wrong. I am using windows 10.

**Comment by foozmeat** [comment]
try setting the locale to the empty string: `''`

**Comment by MuhammadFaizanKhan** [comment]
Yeah it worked but setting the empty string. **Thanks**
